### ISSUE TITLE
Как сделать куки для всего сайта, а не для каждой страницы?

### ISSUE THREAD

**Issue by Medik18** [get-web/google-translate-custom-widget#2]
Для каждой страницы ставятся отдельные куки.
Что делать что бы куки были одни для всего сайта?
Меняешь язык на одной странице, возвращаешся на прошлую страницу, а там опять тот же язык.
Можно ли сделать так, что бы если сменил язык, то это применилось бы ко всему сайту?

**Comment by get-web** [comment]
Попробуйте раскоментировать строку **domain: "Get-Web.Site"** и вписать адрес своего основного домена.

**Comment by Medik18** [comment]
Не помогает.
Сайт пока на субдомене, возможно всё будет работать как нужно когда перенесу сайт на основной домен.

**Comment by get-web** [comment]
На основном домене работать будет. 
Дело в конфигурации сервера, он у вас не разрешает задать куку с поддомена и это в целом правильно, но если есть необходимость менять именно с поддомена, тогда нужно копать в этом направлении.

**Comment by Medik18** [comment]
> На основном домене работать будет.
> Дело в конфигурации сервера, он у вас не разрешает задать куку с поддомена и это в целом правильно, но если есть необходимость менять именно с поддомена, тогда нужно копать в этом направлении.

Благодарю, после всех работ сайт переедет на основной домен, поэтому проблема будет решена.
Желаю вам успеха и благодарю за функционал.

**Comment by get-web** [comment]
Частичное решение на php и дальнейшее обсуждение тут: https://github.com/get-web/google-translate-custom-widget/issues/3
