### ISSUE TITLE
Как запоминать направление перевода для всего сайта со всеми поддиректориями?

### ISSUE THREAD

**Issue by comnetorg** [get-web/google-translate-custom-widget#3]
Сейчас перевод применяется к страницам той директории, где была нажата кнопка перевода. Вероятно, дело в куках и в пути, который в них прописывается. Как правильно настроить виджет, чтобы после нажатия на кнопку перевода на любой странице сайта любой директории перевод применялся и ко ВСЕМ остальным страницам? И, соответственно, сбрасывался при необходимости на дефолтный язык для всего сайта сразу.

сайт/item/1.html - переводятся все страницы в item/ , но не переводятся, например в сайт/info/
Сайт с ЧПУ

**Comment by get-web** [comment]
Сайт должен переводится без каких-либо дополнительных манипуляций.. Попробуйте раскоментировать строку **domain: "Get-Web.Site"** и вписать адрес своего основного домена.

**Comment by comnetorg** [comment]
Спасибо за комментарий, проверил, но это не сработало. У меня была проблема с куками для этого сайта из-за ЧПУ, в которых создаются "поддиректории": 
сайт/item/1.html
сайт/adout/1.html
сайт/1.html и т.д.
Проблема решилась, когда я стал ставить куки так (php):
setcookie("history[$items_id]", "$timestamp", time()+6048000, '/', "$server_name");
Т.е. указывать корневую директорию и домен. Куки стали применяться ко всем директориям. Возможно, в скрипте такая же проблема?

**Comment by get-web** [comment]
> Возможно, в скрипте такая же проблема?

Скорее всего у вас сервер так настроен, что не позволяет создавать куки для основного домена из поддиректорий средствами js даже если явно его указать. Но это нужно смотреть уже на конкретном сервере, если дадите ссылку на свой сайт попробую разобраться.
