### ISSUE TITLE
Перевод сразу

### ISSUE THREAD

**Issue by webair-studio** [get-web/google-translate-custom-widget#4]
Здравствуйте. Спасибо за отличный виджет!

Подскажите.
Я определяю язык браузера пользователя так
`$userlang = substr($_SERVER['HTTP_ACCEPT_LANGUAGE'], 0, 2);`
и если он отличен от языков СНГ, то вывожу флажки.

Как сделать так, чтобы сразу переводить на язык пользователя? И при этом дать возможность пользователю самому выбрать нужный ему язык.
googleTranslateConfig.lang это ведь язык источника? А язык, на который нужно перевести по умолчанию, как передать? 

UPD:
Сделал пока так. Может, кому то будет полезным.
```
$userlang = strtolower(substr($_SERVER['HTTP_ACCEPT_LANGUAGE'], 0, 2));
$rulangs = array('ru','be','uk');
if (!in_array($userlang, $rulangs)){
	if (empty($_COOKIE["googtrans"])){
		setcookie("googtrans", "/ru/".$userlang);
	}
}
```

**Comment by get-web** [comment]
Здравствуйте. 

> googleTranslateConfig.lang это ведь язык источника?

Все верно. В случае если у сайта есть несколько "родных языков" мы можем записывать в это свойство текущий язык, чтобы не переводить его, если он совпадет с языком на который необходимо перевести сайт.

> Как сделать так, чтобы сразу переводить на язык пользователя?

Весь фокус в куках, поэтому все что вам нужно сделать это задать необходимые куки до инициализации виджета либо на бекенде, как вы делаете сейчас, либо на фроте средствами js. 
Для того чтобы отследить сделал ли пользователь выбор языка, можно завести отдельную куку либо просто проверять наличие куки googtrans, так что в целом вы все правильно делаете.

**Comment by get-web** [comment]
В версии v1.0.3 добавлена возможность указать язык на который будет переведен сайт при первом посещении.
